name: "Functional Tests"

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - '*.asciidoc'
  pull_request:

concurrency:
  group: functionalTest-${{ github.ref }}
  cancel-in-progress: true

jobs:
  functionalTest:
    strategy:
      matrix:
        gradle_version:
          - 8.8
          - 8.14.2
          - 9.2.1
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Functional Tests
      run: ./gradlew functionalTest -DgradleVersion=${{ matrix.gradle_version }}
